name: Docker Image CI
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image - Dockerfile
      run: docker build . --file Dockerfiles/Dockerfile --tag surval/docker-certified-associate:example-2
    - name: Build the Docker image - Dockerfile3
      run: docker build . --file Dockerfiles/Dockerfile3 --tag surval/docker-certified-associate:list-repos
    - name: List Docker Images
      run: docker images
    - name: Print env Vars
      run: env
    - name: Unit Tests 1 - Run the docker image
      run: docker run surval/docker-certified-associate:example-2
    - name: Unit Test 2 - Run the docker image
      run: docker run surval/docker-certified-associate:list-repos
    - name: Login to DockerHub
      env:
       DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
       DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - name: Push to DockerHub
      run: |
        docker push surval/docker-certified-associate:example-2
        docker push surval/docker-certified-associate:list-repos
    - name: Login to GitHub Package Registry
      env:
        GITHUB_PACKAGE_REGISTRY_USERNAME: ${{ secrets.GITHUB_PACKAGE_REGISTRY_USERNAME }}
        GITHUB_PACKAGE_REGISTRY_PASSWORD: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
      run: echo "GITHUB_PACKAGE_REGISTRY_TOKEN" |docker login docker.pkg.github.com --username "$GITHUB_PACKAGE_REGISTRY_USERNAME" --password-stdin
    - name: Push to GitHub Package Registry
      run: |
        docker tag surval/docker-certified-associate:example-2 docker.pkg.github.com/suryaval/docker-certified-associate/example-2:1.0.0
        docker push docker.pkg.github.com/suryaval/docker-certified-associate/example-2:1.0.0
