name: Docker Image CI

on:
- pull_request:
  paths:
    - '*'
- push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfiles/Dockerfile --tag my-image-name:$(date +%s)
    - name: List Docker Images
      run: docker images
